### PR TITLE
Line items and notes models

### LINKED ISSUE #35: [3pt] Line items and notes
- [ ] [1pt] Create new Eloquent models `LineItem` and `Note` using `php artisan make:model ModelName -mfsc`
- [ ] [1pt] Write the migrations for `LineItem` and `Note` based on our schema
- [ ] [1pt] Write the relationship functions for `LineItem` and `Note` with `Quote` in the Eloquent Models.

### PR DESCRIPTION
**Pull request by zgjs**
Here are the changes that include the LineItem and Note Models. To test them out, you can run this:
```sh
cd laravel
composer dump-autoload
php artisan tinker
>>> $quotes = \App\Models\Quote::with('line_items', 'notes')->get();
```
Output will look like this:
```json
=> Illuminate\Database\Eloquent\Collection {#4367
     all: [
       App\Models\Quote {#4104
         id: "1",
         customer_id: "6",
         associate_id: "2",
         status: "sanctioned",
         customer_name: "Bell South",
         customer_email: "bookkeeper@bellsouth.net",
         discount_amount: "0",
         discount_percent: "5",
         total_amount: "123.45",
         commission_percent: "0",
         created_at: "2021-04-14 02:01:47",
         updated_at: "2021-04-19 02:01:47",
         line_items: Illuminate\Database\Eloquent\Collection {#4364
           all: [
             App\Models\LineItem {#4368
               id: "1",
               quote_id: "1",
               description: "Cellular tower repair",
               price: "30000",
               quantity: "1",
               created_at: null,
               updated_at: null,
             },
             App\Models\LineItem {#4369
               id: "2",
               quote_id: "1",
               description: "Phone line respooling",
               price: "1234.56",
               quantity: "1",
               created_at: null,
               updated_at: null,
             },
             App\Models\LineItem {#4370
               id: "3",
               quote_id: "1",
               description: "Switchboard cleaning",
               price: "666.66",
               quantity: "1",
               created_at: null,
               updated_at: null,
             },
           ],
         },
         notes: Illuminate\Database\Eloquent\Collection {#4377
           all: [
             App\Models\Note {#4381
               id: "1",
               quote_id: "1",
               secret: "0",
               text: "Order should have a 5% discount",
               created_at: null,
               updated_at: null,
             },
             App\Models\Note {#4382
               id: "2",
               quote_id: "1",
               secret: "1",
               text: "Their book keeper really annoys me! They have been sending me to voicemail.",
               created_at: null,
               updated_at: null,
             },
             App\Models\Note {#4383
               id: "3",
               quote_id: "1",
               secret: "0",
               text: "This is a rush order",
               created_at: null,
               updated_at: null,
             },
           ],
         },
       },
       App\Models\Quote {#4351
         id: "2",
         customer_id: "21",
         associate_id: "2",
         status: "finalized",
         customer_name: "Excelsior Mutants",
         customer_email: "van@celsius.net",
         discount_amount: "25",
         discount_percent: "0",
         total_amount: "234.56",
         commission_percent: "0",
         created_at: "2021-04-16 02:01:47",
         updated_at: "2021-04-19 02:01:47",
         line_items: Illuminate\Database\Eloquent\Collection {#3736
           all: [
             App\Models\LineItem {#4371
               id: "4",
               quote_id: "2",
               description: "Toxic sludge removal",
               price: "1",
               quantity: "1",
               created_at: null,
               updated_at: null,
             },
             App\Models\LineItem {#4372
               id: "5",
               quote_id: "2",
               description: "Excess body part disposal",
               price: "50",
               quantity: "30",
               created_at: null,
               updated_at: null,
             },
             App\Models\LineItem {#4373
               id: "6",
               quote_id: "2",
               description: "Nuclear reactor refueling",
               price: "750000",
               quantity: "2",
               created_at: null,
               updated_at: null,
             },
           ],
         },
         notes: Illuminate\Database\Eloquent\Collection {#4298
           all: [
             App\Models\Note {#4384
               id: "4",
               quote_id: "2",
               secret: "1",
               text: "Order will have a $25 discount after finalized",
               created_at: null,
               updated_at: null,
             },
             App\Models\Note {#4385
               id: "5",
               quote_id: "2",
               secret: "0",
               text: "Contact name is Hubert Farnsworth",
               created_at: null,
               updated_at: null,
             },
             App\Models\Note {#4386
               id: "6",
               quote_id: "2",
               secret: "1",
               text: "OMG THESE GUYS ARE ACTUALLY MUTANTS",
               created_at: null,
               updated_at: null,
             },
           ],
         },
       },
       App\Models\Quote {#4352
         id: "3",
         customer_id: "18",
         associate_id: "2",
         status: "unfinalized",
         customer_name: "South by Southwest",
         customer_email: "bookkeeper@sxsw.com",
         discount_amount: "0",
         discount_percent: "0",
         total_amount: "0",
         commission_percent: "0",
         created_at: "2021-04-19 02:01:47",
         updated_at: "2021-04-19 02:01:47",
         line_items: Illuminate\Database\Eloquent\Collection {#4355
           all: [
             App\Models\LineItem {#4374
               id: "7",
               quote_id: "3",
               description: "Arts and crafts cleanup",
               price: "30",
               quantity: "5",
               created_at: null,
               updated_at: null,
             },
             App\Models\LineItem {#4375
               id: "8",
               quote_id: "3",
               description: "Musical instruments repair",
               price: "100",
               quantity: "100",
               created_at: null,
               updated_at: null,
             },
             App\Models\LineItem {#4376
               id: "9",
               quote_id: "3",
               description: "Fairgrounds trash removal",
               price: "3500",
               quantity: "7",
               created_at: null,
               updated_at: null,
             },
           ],
         },
         notes: Illuminate\Database\Eloquent\Collection {#4362
           all: [
             App\Models\Note {#4387
               id: "7",
               quote_id: "3",
               secret: "1",
               text: "I wish we could charge extra for puke cleanup",
               created_at: null,
               updated_at: null,
             },
             App\Models\Note {#4388
               id: "8",
               quote_id: "3",
               secret: "0",
               text: "Event runs March 16 through March 20",
               created_at: null,
               updated_at: null,
             },
             App\Models\Note {#4389
               id: "9",
               quote_id: "3",
               secret: "1",
               text: "Diplo will be there this year!!",
               created_at: null,
               updated_at: null,
             },
           ],
         },
       },
     ],
   }
   ```

Closes #35

### CODE REVIEW

**Comment by Cyndexz** [comment]
image

**Comment by Cyndexz** [comment]
image

**Review by Cyndexz — APPROVED** [review]
image

**Review by z1868762 — APPROVED** [review]
image

**Review by maxwentmissing — APPROVED** [review]
image

**Pull request merged**
