### PR TITLE
Home Page (signed in)

### LINKED ISSUE #10: [4pt] Home page - signed in
- [x] [2pt] Display a dashboard to signed in users based on their roles. Users should have big icons to take them to pages they have access to, depending on their roles.
- [x] [2pt] If they are a sales associate, show their earned commissions in big text.

### PR DESCRIPTION
**Pull request by Cyndexz**
* Add pictures as buttons
* Add text underneath to lead to the page
* Center dashboard text
* Show accumulated commissions

I would just like for you guys to comment on whether you want something css wise to change or anything like that.

Closes #10

### CODE REVIEW

**Comment by zgjs** [comment]
Here's what I see when I run it:
image
Looks great! Speech bubble is a nice choice for quotes. I updated a row in my database to show the accumulated commission for sales. When I'm logged in as admin.
```sh
echo -e "UPDATE users SET accumulated_commission = '420.69' WHERE id = 2;\nSELECT username,accumulated_commission FROM users;\n" | sqlite3 database/database.sqlite 
admin|0
sales|420.69
clerk|0
```
Two Q's:

* I like the icon for quotes. Can we also add an additional button for **New Quote**? Maybe something with a green plus-sign on it?
* What is the link with the coins icon and the **?** text for?

**Review by zgjs — CHANGES_REQUESTED** [review]
Looks good! Can we also add an additional button for New Quote? Maybe something with a green plus-sign on it?

**Comment by z1868762** [comment]
This looks really good!

**Comment by z1868762** [comment]
> Looks good! Can we also add an additional button for New Quote? Maybe something with a green plus-sign on it?

I think we can probably do that when the user clicks "Quote' on the dashboard.
Do we also need to show the legacy database of previous customers?

**Review by zgjs — APPROVED** [review]

**Pull request merged**
